name = "codeink"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-02-11"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
